# Generated by Django 4.0.3 on 2022-03-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('flavour', models.CharField(max_length=256)),
                ('preference', models.CharField(max_length=256)),
                ('veg', models.BooleanField()),
                ('img', models.CharField(max_length=256)),
            ],
        ),
    ]
