# Generated by Django 4.0.3 on 2022-03-27 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=256)),
                ('pword', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='specialty',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='cook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cook'),
        ),
    ]
