# Generated by Django 4.0.3 on 2022-03-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cook_dish_specialty_dish_cook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=256)),
                ('pword', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=256)),
            ],
        ),
    ]
