# Generated by Django 4.0.3 on 2022-03-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='cook',
            name='role',
            field=models.BooleanField(null=True),
        ),
    ]
