# Generated by Django 4.0.3 on 2022-03-27 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_delete_customer_cook_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cook',
            name='pword',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='uname',
        ),
        migrations.AddField(
            model_name='cook',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
